baseURL = "https://index.zhoulouzi.com/"
languageCode = "en-us"
title = "Index pages"
theme = "slate"
googleAnalytics = "UA-110602463-2"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "collaborative"
tag = "collaborative"
icon = "star"
