baseURL = "https://index.zhoulouzi.com/"
languageCode = "en-us"
title = "Index pages"
theme = "slate"
googleAnalytics = "UA-110602463-2"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "collaborative"
tag = "collaborative"
icon = "star"

[[ params.nav ]]
name = "coding"
tag = "coding"
icon = "code"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "users"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "twitch"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-bag"