apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: index-page
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # tls:
  # - hosts:
  #   - index.cluster.local
  #   secretName: index-page
  rules:
  - host: index.cluster.local
    http:
      paths:
      - backend:
          serviceName: index-page
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: index-page
  labels:
spec:
  selector:
    app: index-page
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: index-page
spec:
  selector:
    matchLabels:
      app: index-page
  template:
    metadata:
      labels:
        app: index-page
    spec:
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
      containers:
      - name: index-page
        image: ${env.DOCKER_REPO}:${env.BUILD_ID}"
        ports:
        - containerPort: 80
          protocol: TCP