apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: index-page
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
spec:
  tls:
  - hosts:
    - index.zhoulouzi.com
    secretName: index-page
  rules:
  - host: index.zhoulouzi.com
    http:
      paths:
      - backend:
          serviceName: index-page
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: index-page
  labels:
spec:
  selector:
    app: index-page
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-page
spec:
  selector:
    matchLabels:
      app: index-page
  template:
    metadata:
      labels:
        app: index-page
    spec:
      containers:
      - name: index-page
        image: zhoulouzi/index-page:latest
        ports:
        - containerPort: 80
          protocol: TCP